## Pandas Extras -- 1

### 1) Creating a dataframe using np.arange and np.reshape and assigning indices to rows and columns
### 2) Using df.to_csv() to convert dataframe to csv
### 3) Using loc and iloc to access rows and columns
### 4) Converting dataframes to numpy arrays using iloc and .values
### 5) Handling missing values
### 6) Finding unique categories in a column using value_counts[Method-1] and unique()[Method-2]
### 7) df.head(), df.info(), df.describe()
### 8) Reading CSV files with various parameters..
- sep parameter
- StringIO, BytesIO and use of StringIO to read CSV
- usecols
- Specifying data types to columns using dtype
- index_col
- escapechar

### 9) Reading URL's to CSV




In [131]:
import numpy as np 
import pandas as pd 

In [132]:
#1--Forming a dataframe..

df = pd.DataFrame(np.arange(0, 30).reshape(5,6), index = ["Row1", "Row2", "Row3", "Row4", "Row5"], columns = ["Column1", "Column2", "Column3", "Column4", "Column5", "Column6"])
print(df)

      Column1  Column2  Column3  Column4  Column5  Column6
Row1        0        1        2        3        4        5
Row2        6        7        8        9       10       11
Row3       12       13       14       15       16       17
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29


In [133]:
#2-- 
df.to_csv("Test1.csv")

In [134]:
#3-- 

print(df.loc["Row1"])
type(df.loc["Row1"])

print(df.iloc[0:3, 3:])
type(df.iloc[0:3, 3:])

Column1    0
Column2    1
Column3    2
Column4    3
Column5    4
Column6    5
Name: Row1, dtype: int64
      Column4  Column5  Column6
Row1        3        4        5
Row2        9       10       11
Row3       15       16       17


pandas.DataFrame

In [135]:
#4-- Converting dataframe to np array

print(df.iloc[:,:].values)
type(df.iloc[:,:].values)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


numpy.ndarray

In [136]:
#5-- Checking if there are any missing values in the dataframe--

print(df.isnull().sum())

#If there were missing values, they can be handled by df.fillna or df.dropna

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
Column6    0
dtype: int64


In [137]:
#6-- To find the unique categories in a column

#M1--

print(df["Column3"].value_counts())

#M2--

print(df["Column3"].unique())
type(df["Column3"].unique())

Column3
2     1
8     1
14    1
20    1
26    1
Name: count, dtype: int64
[ 2  8 14 20 26]


numpy.ndarray

In [138]:
#7-- 

df_2 = pd.read_csv(r"D:\ML_krish_naik\Data-Sets\mercedesbenz.csv")
print(df_2.head(), end = "\n\n")
print(df_2.info(), end = "\n\n")
print(df_2.describe(), end = "\n\n") #df.describe works only for numerical values

   ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB
None

                ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
m

In [139]:
#8(a)

# df_3 = pd.read_csv("Test3.csv") #Shows error

df_3 = pd.read_csv("Test3.csv", sep = ";")
print(df_3)

  Unnamed: 0  Column1  Column2  Column3  Column4  Column5  Column6
0       Row1        0        1        2        3        4        5
1       Row2        6        7        8        9       10       11
2       Row3       12       13       14       15       16       17
3       Row4       18       19       20       21       22       23
4       Row5       24       25       26       27       28       29


In [140]:
#8(e)

df_4 = pd.read_csv("Test3.csv", sep = ";", index_col="Unnamed: 0")
print(df_4) #USING index_col

      Column1  Column2  Column3  Column4  Column5  Column6
Row1        0        1        2        3        4        5
Row2        6        7        8        9       10       11
Row3       12       13       14       15       16       17
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29


In [141]:
#8(b)

from io import StringIO , BytesIO

data = ("Column1,Column2,Column3\n"
         "1,2,3\n"
         "a,b,c\n")
print(type(data))
df_5 = pd.read_csv(StringIO(data))
print(df_5)


<class 'str'>
  Column1 Column2 Column3
0       1       2       3
1       a       b       c


In [142]:
#8(c)

df_6 = pd.read_csv(StringIO(data), usecols=lambda x : x.upper() in ['COLUMN1', 'COLUMN3']) #same as usecols = ['Column1', 'Column3']
print(df_6) #for reading only certain columns..

  Column1 Column3
0       1       3
1       a       c


In [143]:

df_7 = pd.DataFrame(np.arange(0,20).reshape(5,4))
print(df_7)
df_7.to_csv("Test2.csv")

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19


In [144]:
#8(d)-- Specifying columns data types..

df_8 = pd.read_csv("Test2.csv", dtype = float)
df_8 = df_8.drop(columns=['Unnamed: 0'])
print(df_8)

      0     1     2     3
0   0.0   1.0   2.0   3.0
1   4.0   5.0   6.0   7.0
2   8.0   9.0  10.0  11.0
3  12.0  13.0  14.0  15.0
4  16.0  17.0  18.0  19.0


In [145]:
df_9 = pd.read_csv("Test2.csv", dtype = {0: int, 1: float, 2:'Int64'})
df_9 = df_9.drop(columns=["Unnamed: 0"]) #0 -- got dropped that;s why first column has dtype = float..
print(df_9, end = "\n\n")
print(df_9.dtypes)

      0   1   2   3
0   0.0   1   2   3
1   4.0   5   6   7
2   8.0   9  10  11
3  12.0  13  14  15
4  16.0  17  18  19

0    float64
1      Int64
2      int64
3      int64
dtype: object


In [146]:
#8(e) -- Use of index_col = False

data1 = ('a,b,c\n'
        '1,2,3,\n'
         '4,5,6,')

df_10 = pd.read_csv(StringIO(data1))
print(df_10, end = "\n\n")

df_11 = pd.read_csv(StringIO(data1), index_col=False)
print(df_11)


   a  b   c
1  2  3 NaN
4  5  6 NaN

   a  b  c
0  1  2  3
1  4  5  6


In [147]:
#8(f) -- Quoting and Escape characters..

data2 = ('a,b\n"Hello \\"Bob\\" nice to see you", 5\n')

df_12 = pd.read_csv(StringIO(data2), escapechar='\\')
print(df_12)

                             a  b
0  Hello "Bob" nice to see you  5


In [148]:
#9-- Reading URL to CSV -- 
#Check the separator used in the url..

#In the example given below -- \t(tab space) is the separator..

# df_13 = pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item", sep = '\t')
# print(df_13.head())

#The code above is correct -- it gives an error due to issue with website server..
